name: xplore
description: xplore superapp
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async_redux: ^12.0.0
  cloud_firestore: ^2.5.0
  concentric_transition: ^1.0.1+1
  cupertino_icons: ^1.0.2
  debug_logger: ^0.0.23
  equatable: ^2.0.3
  firebase_analytics: ^8.3.0
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  flutter:
    sdk: flutter
  freezed: ^0.14.2
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3
  lottie: ^1.1.0
  rxdart: ^0.27.1
  sqflite: ^2.0.0+3
  intl_phone_number_input: ^0.7.0+2
  connectivity: ^3.0.6



dev_dependencies:
  build_runner: ^2.0.4
  built_value_generator: ^8.0.2
  flutter_test:
    sdk: flutter
  lint: 1.5.3
  mockito: ^5.0.1
  mocktail_image_network: ^0.1.0
  test: ^1.16.5

flutter:
  uses-material-design: true
  assets:
    - assets/

