name: xplore
description: xplore superapp
publish_to: "none"

version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async_redux: ^13.3.1
  cloud_firestore: ^3.1.10
  concentric_transition: ^1.0.1+1
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  firebase_analytics: ^9.1.2
  firebase_auth: ^3.3.9
  firebase_crashlytics: ^2.5.3
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  dependencies:
  flutter_native_splash: ^2.1.1
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  logger: ^1.1.0
  lottie: ^1.2.2
  persistent_bottom_nav_bar: ^4.0.2
  pin_code_fields: ^7.3.0
  rxdart: ^0.27.3
  sqflite: ^2.0.2
  intl_phone_number_input: ^0.7.0+2
  connectivity_plus: ^2.2.1

dev_dependencies:
  build_runner:
  built_value_generator:
  # flutter_test:
  #   sdk: flutter
  # flutter_driver:
  #   sdk: flutter
  # integration_test:
  #   sdk: flutter
  lint: 
  import_sorter: ^4.6.0
  # mockito: 
  # mocktail_image_network: 
  # test: 

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/onboarding/
    - assets/appIcon/playstore.png

