name: shamiri
description: Built for scale, made for conveniance.
publish_to: "none"
# Increment
version: 1.1.3

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  async_redux: ^15.0.0
  cloud_firestore: ^3.1.17
  connectivity_plus: ^2.3.0
  cupertino_icons: ^1.0.4
  design:
    path: "./design"
  equatable: ^2.0.3
  firebase_analytics: ^9.1.9
  firebase_auth: ^3.3.19
  firebase_crashlytics: ^2.8.1
  firebase_core: ^1.17.1
  flutter:
    sdk: flutter
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  intl: ^0.17.0
  logger: ^1.1.0
  lottie: ^1.3.0
  pin_code_fields: ^7.4.0
  progress_state_button: ^1.0.4
  rxdart: ^0.27.3
  salomon_bottom_bar: ^3.3.1
  shimmer: ^2.0.0
  sqflite: ^2.0.2+1

dev_dependencies:
  build_runner: ^2.1.11
  built_value_generator: ^8.3.2
  flutter_native_splash: ^2.2.1
  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  import_sorter: ^4.6.0
  lint:

flutter_native_splash: 
  image: assets/appIcon/playstore.png
  color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/onboarding/
    - assets/appIcon/playstore.png
    - assets/general/xplore_loader.json
