name: xplore
description: xplore superapp
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async_redux: ^12.0.0
  cupertino_icons: ^1.0.2
  debug_logger: ^0.0.23
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  freezed: ^0.14.2
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3
  sqflite: ^2.0.0+3


dev_dependencies:
  build_runner: ^2.0.4
  built_value_generator: ^8.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
