name: CI Workflow

on: [push]

jobs:
  run-tests-and-coverage:
    name: Analyze, test and report coverage
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12"
      - uses: actions/setup-python@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
          flutter-version: "3.0.0"

      - name: Install flutter dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Analyze and Test
        run: |
          flutter analyze
